version: "3.7"

services:
  server:
    build: server
    container_name: test-page-server
    network_mode: "host"
    ports:
      - 8087:8087
      - 8081:8081
    volumes:
      - /tmp:/tmp

  nginx:
    build: nginx
    network_mode: "host"

