#!/bin/bash

# install sudo
apt-get update && apt-get -y install sudo
apt-get -y install npm

cd $JENKINS_HOME/nginx/react_web
sudo npm install
sudo npm build


# # remove container and image
# sudo docker stop test-page
# sudo docker rm test-page
# sudo docker rmi test-page:latest

# # build image and run container
# cd nginx
# sudo docker build -t test-page:latest .
# sudo docker run -d --network="host" --name test-page test-page:latest 
