#!/bin/bash

# install sudo
apt-get update && apt-get -y install sudo
apt-get -y install npm
npm install -g npm@8.16.0
curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt-get -y install nodejs

cd $JENKINS_HOME/workspace/forTest/nginx/react_web
sudo npm install
sudo npm build

mkdir $JENKINS_HOME/workspace/forTest/nginx/temp
cp -a $JENKINS_HOME/workspace/forTest/nginx/react_web/build $JENKINS_HOME/workspace/forTest/nginx/temp

# # remove container and image
# sudo docker stop test-page
# sudo docker rm test-page
# sudo docker rmi test-page:latest

# # build image and run container
# cd nginx
# sudo docker build -t test-page:latest .
# sudo docker run -d --network="host" --name test-page test-page:latest 
