#!/bin/bash
sudo docker stop test-page
sudo docker rm test-page
sudo docker rmi test-page:latest
sudo docker build -t test-page:latest .
sudo docker run -d --network="host" --name test-page test-page:latest 
