#!/bin/bash

# gradle build
cd $JENKINS_HOME/workspace/forTest/server/demo
chmod +x ./gradlew
./gradlew build

cd $JENKINS_HOME/workspace/forTest/server/demo/build/libs

cp $JENKINS_HOME/workspace/forTest/server/demo/build/libs/demo.jar $JENKINS_HOME/workspace/forTest/server/

#TODO: build server image, container
sudo docker-compose down
sudo docker-compose up --build -d